CREATE TABLE IF NOT EXISTS roles (
    id   BIGSERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO roles (name) VALUES ('STUDENT')  ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('TRAINER')  ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ADMIN')    ON CONFLICT DO NOTHING;
