package com.vcube.academy.service;

import com.vcube.academy.dto.notification.NotificationDto;
import com.vcube.academy.entity.StudentNotification;
import com.vcube.academy.enums.NotificationType;
import com.vcube.academy.repository.StudentNotificationRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class NotificationService {

    private final StudentNotificationRepository notificationRepository;

    @Transactional
    public List<NotificationDto> getStudentNotifications(Long studentId, boolean unreadOnly) {
        seedInitialNotificationsIfEmpty(studentId);

        List<StudentNotification> notifications;
        if (unreadOnly) {
            notifications = notificationRepository.findByStudentIdAndIsReadFalseOrderByCreatedAtDesc(studentId);
        } else {
            notifications = notificationRepository.findByStudentIdOrderByCreatedAtDesc(studentId);
        }

        return notifications.stream()
                .map(this::toDto)
                .collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public long getUnreadCount(Long studentId) {
        return notificationRepository.countByStudentIdAndIsReadFalse(studentId);
    }

    @Transactional
    public void markAsRead(Long studentId, Long notificationId) {
        notificationRepository.findById(notificationId)
                .filter(n -> n.getStudentId().equals(studentId))
                .ifPresent(n -> {
                    n.setIsRead(true);
                    notificationRepository.save(n);
                });
    }

    @Transactional
    public void markAllAsRead(Long studentId) {
        List<StudentNotification> unread = notificationRepository.findByStudentIdAndIsReadFalseOrderByCreatedAtDesc(studentId);
        unread.forEach(n -> n.setIsRead(true));
        notificationRepository.saveAll(unread);
    }

    @Transactional
    public NotificationDto createNotification(Long studentId, String title, String message, NotificationType type, String actionRoute) {
        StudentNotification n = StudentNotification.builder()
                .studentId(studentId)
                .title(title)
                .message(message)
                .notificationType(type)
                .actionRoute(actionRoute)
                .isRead(false)
                .createdAt(LocalDateTime.now())
                .build();
        return toDto(notificationRepository.save(n));
    }

    private void seedInitialNotificationsIfEmpty(Long studentId) {
        if (notificationRepository.findByStudentIdOrderByCreatedAtDesc(studentId).isEmpty()) {
            createNotification(
                    studentId,
                    "New Matching Job: Java Backend Engineer",
                    "A new job matching your Java Full Stack profile is live on the VCUBE placement portal.",
                    NotificationType.JOB_MATCH,
                    "/student/jobs"
            );
            createNotification(
                    studentId,
                    "Daily Preparation Routine Ready",
                    "Your 7 high-yield daily tasks for today have been generated by AI Career Copilot.",
                    NotificationType.DAILY_PLAN_REMINDER,
                    "/student/career/daily-plan"
            );
            createNotification(
                    studentId,
                    "TCS NQT Placement Paper Live",
                    "Practice the full-length TCS NQT Multi-Section Examination Paper with real-time timers.",
                    NotificationType.PLACEMENT_PAPER_ALERT,
                    "/student/placement-papers"
            );
        }
    }

    private NotificationDto toDto(StudentNotification entity) {
        return NotificationDto.builder()
                .id(entity.getId())
                .title(entity.getTitle())
                .message(entity.getMessage())
                .notificationType(entity.getNotificationType().name())
                .actionRoute(entity.getActionRoute())
                .isRead(entity.getIsRead())
                .createdAt(entity.getCreatedAt())
                .build();
    }
}
